#!/usr/bin/env python3
"""Generate shell commands for Unlearn-Sparse reproduction runs."""

from __future__ import annotations

import argparse
import shlex
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

UNLEARN_METHODS = {
    "retrain": ["--unlearn", "retrain", "--unlearn_epochs", "160", "--unlearn_lr", "0.1"],
    "FT": ["--unlearn", "FT", "--unlearn_epochs", "10", "--unlearn_lr", "0.01"],
    "GA": ["--unlearn", "GA", "--unlearn_epochs", "5", "--unlearn_lr", "0.0001"],
    "fisher_new": ["--unlearn", "fisher_new", "--alpha", "0.2"],
    "wfisher": ["--unlearn", "wfisher", "--alpha", "0.2"],
    "FT_prune": [
        "--unlearn",
        "FT_prune",
        "--unlearn_epochs",
        "10",
        "--unlearn_lr",
        "0.01",
        "--alpha",
        "0.2",
    ],
}


@dataclass(frozen=True)
class Scenario:
    name: str
    class_to_replace: int
    num_indexes_to_replace: int


def shell_join(parts: list[str]) -> str:
    return " ".join(shlex.quote(str(part)) for part in parts)


def parse_seeds(value: str) -> list[int]:
    seeds = [int(item.strip()) for item in value.split(",") if item.strip()]
    if not seeds:
        raise argparse.ArgumentTypeError("at least one seed is required")
    return seeds


def train_cmd(args, *, dataset: str, arch: str, seed: int, save_dir: Path, sparse: bool = True) -> list[str]:
    pruning_times = "1" if sparse else "0"
    return [
        "python",
        "-u",
        "main.py",
        "train",
        "--profile",
        "imp",
        "--data",
        args.data,
        "--dataset",
        dataset,
        "--arch",
        arch,
        "--save_dir",
        str(save_dir),
        "--prune_type",
        "rewind_lt",
        "--rewind_epoch",
        str(args.rewind_epoch),
        "--rate",
        "0.95",
        "--pruning_times",
        pruning_times,
        "--workers",
        str(args.workers),
        "--seed",
        str(seed),
        "--train_seed",
        str(seed),
        "--epochs",
        str(args.epochs),
    ]


def unlearn_cmd(
    args,
    *,
    dataset: str,
    arch: str,
    seed: int,
    save_dir: Path,
    mask_path: Path,
    scenario: Scenario,
    method: str,
) -> list[str]:
    cmd = [
        "python",
        "-u",
        "main.py",
        "unlearn",
        "--data",
        args.data,
        "--dataset",
        dataset,
        "--arch",
        arch,
        "--save_dir",
        str(save_dir),
        "--mask",
        str(mask_path),
        "--class_to_replace",
        str(scenario.class_to_replace),
        "--num_indexes_to_replace",
        str(scenario.num_indexes_to_replace),
        "--workers",
        str(args.workers),
        "--seed",
        str(seed),
    ]
    cmd.extend(UNLEARN_METHODS[method])
    return cmd


def emit_header(args) -> list[str]:
    return [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by .codex/skills/unlearn-sparse-repro/scripts/generate_repro_commands.py",
        "# Review GPU placement and storage paths before launching full runs.",
        "",
        f"mkdir -p {shlex.quote(args.runs)}",
        "",
    ]


def emit_smoke(args) -> list[str]:
    smoke_args = argparse.Namespace(**vars(args))
    smoke_args.epochs = 2
    smoke_args.rewind_epoch = 1
    seed = args.seeds[0]
    save_dir = Path(args.runs) / "smoke_cifar10_resnet18" / f"seed_{seed}"
    mask_path = save_dir / "1model_SA_best.pth.tar"
    scenario = Scenario("class0", 0, 4500)
    lines = ["# Smoke test: validates command plumbing only; not paper-equivalent."]
    lines.append(shell_join(train_cmd(smoke_args, dataset="cifar10", arch="resnet18", seed=seed, save_dir=save_dir)))
    ft = unlearn_cmd(
        smoke_args,
        dataset="cifar10",
        arch="resnet18",
        seed=seed,
        save_dir=save_dir,
        mask_path=mask_path,
        scenario=scenario,
        method="FT",
    )
    ft[ft.index("--unlearn_epochs") + 1] = "1"
    lines.append(shell_join(ft))
    lines.append("")
    return lines


def emit_core(args) -> list[str]:
    scenarios = [
        Scenario("classwise_class0", 0, 4500),
        Scenario("random_10pct", -1, 4500),
    ]
    methods = ["retrain", "FT", "GA", "fisher_new", "wfisher", "FT_prune"]
    lines = ["# Core CIFAR-10/ResNet-18 reproduction commands."]
    for seed in args.seeds:
        train_dir = Path(args.runs) / "core" / "cifar10_resnet18" / f"seed_{seed}" / "train"
        lines.append(shell_join(train_cmd(args, dataset="cifar10", arch="resnet18", seed=seed, save_dir=train_dir)))
        masks = {
            "dense": train_dir / "0model_SA_best.pth.tar",
            "sparse95": train_dir / "1model_SA_best.pth.tar",
        }
        for scenario in scenarios:
            for mask_name, mask_path in masks.items():
                for method in methods:
                    run_dir = Path(args.runs) / "core" / "cifar10_resnet18" / f"seed_{seed}" / scenario.name / mask_name / method
                    lines.append(
                        shell_join(
                            unlearn_cmd(
                                args,
                                dataset="cifar10",
                                arch="resnet18",
                                seed=seed,
                                save_dir=run_dir,
                                mask_path=mask_path,
                                scenario=scenario,
                                method=method,
                            )
                        )
                    )
    lines.append("")
    return lines


def emit_appendix(args) -> list[str]:
    configs = [
        ("cifar10", "vgg16_bn", 4500, 4500),
        ("cifar100", "resnet18", 450, 4500),
        ("svhn", "resnet18", 4454, 6593),
    ]
    lines = ["# Appendix-style dataset/model sweeps exposed by the current CLI."]
    for dataset, arch, class_count, random_count in configs:
        for seed in args.seeds:
            train_dir = Path(args.runs) / "appendix" / f"{dataset}_{arch}" / f"seed_{seed}" / "train"
            lines.append(shell_join(train_cmd(args, dataset=dataset, arch=arch, seed=seed, save_dir=train_dir)))
            for scenario in [
                Scenario("classwise_class0", 0, class_count),
                Scenario("random_10pct", -1, random_count),
            ]:
                for method in ["FT", "GA", "FT_prune"]:
                    run_dir = Path(args.runs) / "appendix" / f"{dataset}_{arch}" / f"seed_{seed}" / scenario.name / method
                    lines.append(
                        shell_join(
                            unlearn_cmd(
                                args,
                                dataset=dataset,
                                arch=arch,
                                seed=seed,
                                save_dir=run_dir,
                                mask_path=train_dir / "1model_SA_best.pth.tar",
                                scenario=scenario,
                                method=method,
                            )
                        )
                    )
    lines.append("")
    return lines


def emit_backdoor(args) -> list[str]:
    lines = ["# Backdoor/Trojan cleanse sparsity sweep."]
    for seed in args.seeds:
        for rate in ["0", "0.75", "0.90", "0.95", "0.99"]:
            tag = rate.replace(".", "p")
            save_dir = Path(args.runs) / "backdoor" / f"seed_{seed}" / f"sparsity_{tag}"
            cmd = [
                "python",
                "-u",
                "main.py",
                "backdoor",
                "--data",
                args.data,
                "--dataset",
                "cifar10",
                "--arch",
                "resnet18",
                "--save_dir",
                str(save_dir),
                "--mask",
                str(save_dir / "mask.pt"),
                "--unlearn",
                "FT",
                "--num_indexes_to_replace",
                "4500",
                "--class_to_replace",
                "0",
                "--trigger_size",
                "4",
                "--rate",
                rate,
                "--workers",
                str(args.workers),
                "--seed",
                str(seed),
            ]
            lines.append(shell_join(cmd))
    lines.append("")
    return lines


def emit_imagenet(args) -> list[str]:
    lines = [
        "# ImageNet commands require HuggingFace ImageNet access plus train/val label tensors.",
        "# Generate labels with: python src/dataio/imagenet.py",
    ]
    for seed in args.seeds:
        save_dir = Path(args.runs) / "imagenet_resnet18" / f"seed_{seed}"
        cmd = [
            "python",
            "-u",
            "main.py",
            "unlearn",
            "--dataset",
            "imagenet",
            "--imagenet_arch",
            "--arch",
            "resnet18",
            "--save_dir",
            str(save_dir),
            "--mask",
            str(save_dir / "0model_SA_best.pth.tar"),
            "--class_to_replace",
            "0",
            "--unlearn",
            "FT",
            "--unlearn_epochs",
            "5",
            "--unlearn_lr",
            "0.001",
            "--batch_size",
            "1024",
            "--input_size",
            "224",
            "--train_y_file",
            "./labels/train_ys.pth",
            "--val_y_file",
            "./labels/val_ys.pth",
            "--seed",
            str(seed),
        ]
        lines.append(shell_join(cmd))
    lines.append("")
    return lines


def transfer_cmd(
    args,
    *,
    seed: int,
    target_dataset: str,
    source_checkpoint: Path,
    save_dir: Path,
    split_file: Optional[str] = None,
) -> list[str]:
    cmd = [
        "python",
        "-u",
        "main.py",
        "transfer",
        "--arch",
        "resnet18",
        "--imagenet_arch",
        "--source_checkpoint",
        str(source_checkpoint),
        "--source_num_classes",
        "1000",
        "--target_dataset",
        target_dataset,
        "--target_data",
        args.data,
        "--save_dir",
        str(save_dir),
        "--transfer_method",
        args.transfer_method,
        "--transfer_epochs",
        str(args.transfer_epochs),
        "--transfer_lr",
        str(args.transfer_lr),
        "--transfer_optimizer",
        "Adam",
        "--transfer_resolution",
        "224",
        "--batch_size",
        str(args.transfer_batch_size),
        "--transfer_test_batch_size",
        str(args.transfer_test_batch_size),
        "--workers",
        str(args.workers),
        "--seed",
        str(seed),
    ]
    if split_file:
        cmd.extend(["--transfer_split_file", split_file])
    return cmd


def emit_transfer(args) -> list[str]:
    lines = [
        "# Transfer-learning commands for the paper's ImageNet -> OxfordPets/SUN397 setup.",
        "# Run ImageNet source/unlearning first, then point --source_checkpoint to the resulting checkpoint.",
        "# SUN397 paper-equivalent reproduction should use a CoOp-style split via --sun397-split.",
    ]
    targets = [
        ("oxfordpets", args.oxfordpets_split or None),
        ("sun397", args.sun397_split or None),
    ]
    for seed in args.seeds:
        base_dir = Path(args.runs) / "transfer" / f"seed_{seed}"
        source_checkpoint = (
            Path(args.runs)
            / "imagenet_resnet18"
            / f"seed_{seed}"
            / "0model_SA_best.pth.tar"
        )
        for target_dataset, split_file in targets:
            save_dir = base_dir / target_dataset / "source"
            lines.append(
                shell_join(
                    transfer_cmd(
                        args,
                        seed=seed,
                        target_dataset=target_dataset,
                        source_checkpoint=source_checkpoint,
                        save_dir=save_dir,
                        split_file=split_file,
                    )
                )
            )

        for forget_count in ["100", "200", "300"]:
            source_checkpoint = (
                Path(args.runs)
                / "imagenet_resnet18"
                / f"seed_{seed}"
                / f"forget_{forget_count}"
                / "FT_prunecheckpoint.pth.tar"
            )
            for target_dataset, split_file in targets:
                save_dir = base_dir / target_dataset / f"forget_{forget_count}"
                lines.append(
                    shell_join(
                        transfer_cmd(
                            args,
                            seed=seed,
                            target_dataset=target_dataset,
                            source_checkpoint=source_checkpoint,
                            save_dir=save_dir,
                            split_file=split_file,
                        )
                    )
                )
    lines.append("")
    return lines


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--suite",
        choices=[
            "smoke",
            "core",
            "appendix",
            "backdoor",
            "imagenet",
            "transfer",
            "all",
        ],
        default="core",
    )
    parser.add_argument("--data", default="./data")
    parser.add_argument("--runs", default="./runs/repro")
    parser.add_argument("--workers", type=int, default=8)
    parser.add_argument("--seeds", type=parse_seeds, default=parse_seeds("1"))
    parser.add_argument("--epochs", type=int, default=182)
    parser.add_argument("--rewind-epoch", type=int, default=8)
    parser.add_argument("--transfer-method", choices=["lp", "ff"], default="lp")
    parser.add_argument("--transfer-epochs", type=int, default=200)
    parser.add_argument("--transfer-lr", type=float, default=1e-4)
    parser.add_argument("--transfer-batch-size", type=int, default=128)
    parser.add_argument("--transfer-test-batch-size", type=int, default=1024)
    parser.add_argument("--oxfordpets-split", default="")
    parser.add_argument("--sun397-split", default="")
    args = parser.parse_args()

    emitters = {
        "smoke": emit_smoke,
        "core": emit_core,
        "appendix": emit_appendix,
        "backdoor": emit_backdoor,
        "imagenet": emit_imagenet,
        "transfer": emit_transfer,
    }
    suites = list(emitters) if args.suite == "all" else [args.suite]

    lines = emit_header(args)
    for suite in suites:
        lines.extend(emitters[suite](args))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
